[project]
name = "src-app-package"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "holm>=0.7.2",
    "poethepoet>=0.38.0",
    "uvicorn>=0.40.0",
]

[tool.poe.tasks]
start.cmd = "uvicorn my_app.main:app --reload"
start.cwd = "src"
