[project]
name = "src-app-package2"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "holm>=0.7.2",
    "uvicorn>=0.40.0",
]

[tool.uv]
package = true

[project.scripts]
my_app = "my_app.main:run_app"
